version: '3.8'

services:
  api:
    container_name: api
    build: ./backend/api
    restart: always
    expose:
      - 3333
    ports:
      - "3333:3333"
    network_mode: host

  graphql: 
    container_name: graphql
    build: ./backend/graphql
    restart: always
    expose:
     - 4000
    ports:
      - "4000:4000"
    depends_on:
      - api
    network_mode: host

  react: 
    container_name: react
    build: ./frontend
    restart: always
    expose:
     - 5173
    ports:
      - "5173:5173"
    depends_on:
      - graphql
    network_mode: host
    